export const schoolType = [
  "École maternelle",
  "École primaire",
  "École secondaire",
  "Université",
  "École publique",
  "École privée",
  "École confessionnelle (catholique, protestante, etc.)",
  "Enseignement général",
  "Enseignement technique",
  "Enseignement professionnel",
  "École normale (formation des enseignants)",
  "École francophone",
  "École anglophone",
  "École bilingue",
  "École laïque",
  "École religieuse",
];

export const city = [
  "Yaoundé",
  "Douala",
  "Garoua",
  "Maroua",
  "Bamenda",
  "Bafoussam",
  "Ngaoundéré",
  "Bertoua",
  "Ebolowa",
  "Kribi",
  "Limbe",
  "Edéa",
  "Kumba",
  "Nkongsamba",
  "Dschang",
  "Foumban",
  "Bafang",
  "Mbouda",
  "Sangmélima",
  "Mbalmayo",
  "Obala",
  "Monatélé",
  "Eséka",
  "Akonolinga",
  "Yagoua",
  "Guider",
  "Tiko",
  "Wum",
];

export const country = [
  "Algérie",
  "Angola",
  "Bénin",
  "Botswana",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cameroun",
  "République centrafricaine",
  "Tchad",
  "Comores",
  "République du Congo",
  "République démocratique du Congo",
  "Djibouti",
  "Égypte",
  "Érythrée",
  "Eswatini",
  "Éthiopie",
  "Gabon",
  "Gambie",
  "Ghana",
  "Guinée",
  "Guinée-Bissau",
  "Guinée équatoriale",
  "Kenya",
  "Lesotho",
  "Liberia",
  "Libye",
  "Madagascar",
  "Malawi",
  "Mali",
  "Maroc",
  "Maurice",
  "Mauritanie",
  "Mozambique",
  "Namibie",
  "Niger",
  "Nigeria",
  "Ouganda",
  "Rwanda",
  "Sao Tomé-et-Principe",
  "Sénégal",
  "Seychelles",
  "Sierra Leone",
  "Somalie",
  "Soudan",
  "Soudan du Sud",
  "Tanzanie",
  "Togo",
  "Tunisie",
  "Zambie",
  "Zimbabwe",
  "Afrique du Sud",
];
